languages:
  - label: Русский
    flag: ru
    code: ru
  - label: English
    flag: en
    code: en

assets: "**/*.svg"

redirects:
  - from: /
    to: help.ru
    normalize: false
  - from: /
    to: help
